name: Assign PR to Creator

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to Creator
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request
            const creator = pr.user.login
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [creator]
            })
