name: Python Black
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check
        id: check
        uses: psf/black@stable
        continue-on-error: true
      - name: run black
        id: run
        if: always() && steps.check.outcome == 'failure'
        uses: psf/black@stable
        with:
          options: --diff
      - name: Set black branch name
        if: always() && steps.run.outcome == 'success'
        id: vars
        run: |
          branch_name="black-patches/${{ github.head_ref }}"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: always() && steps.check.outputs.exit-code == 1
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: black action fixes
          title: Fixes by black action
          body: This is an auto-generated PR with fixes by black.
          labels: black, automated pr
          branch: ${{ steps.vars.outputs.branch_name }}
